#!/bin/bash
## \file    batch.sh
#  \author  Scott Wales (scott.wales@unimelb.edu.au)
#  \brief   Generate a series of UM jobs from a single base
#  
#  Copyright 2013 ARC Centre of Excellence for Climate System Science
#  
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  
#      http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  

function usage {
    echo "$0: Submit multiple UM jobs with different SST ancils"
    echo "Usage: $0 BASE < ANCILS"
    echo "    BASE: Processed UM job from the umui_runs directory"
    echo "    ANCILS: List of SST ancil files"
}

options=$(getopt --options h --longoptions help -- "$@")
eval set -- "$options"

while true; do
    case "$1" in
        -h|--help)
            usage; exit; shift ;;
        --)
            shift; break ;;
    esac
done

if [ "$#" -lt 1 ]; then
    echo "ERROR: No base directory" >&2
    usage
    exit 1
fi

basisdir=$1
basis=$(basename $basisdir)

echo "Reading SST filenames from standard input..."

while read sst_file ; do
    # Store the files in a separate directory so they're not deleted
    # by run scripts
    jobdir=~/um_batch/$basis-$(basename $sst_file)
    mkdir -p $(dirname $jobdir)
    cp -r $basisdir $jobdir

    # Use the files in $jobdir
    sed -i $jobdir/umuisubmit_run -e 's|\(JOBDIR=\).*|\1'$jobdir'|'

    # Change the SST ancil file used in the input namelists to $file
    sed -i $jobdir/INITHIS -e 's|SSTIN : [^'"'"']*|SSTIN : '$sst_file'|'

    # Change the output path
    dataw=\$DATAOUTPUT/\$USER/\$RUNID-$sst_file
    sed -i $jobdir/umuisubmit_run -e 's|\(UM_DATAW=\).*|\1'$dataw'|' \
                                  -e 's|\(UM_DATAM=\).*|\1'$dataw'|'

    # Submit the job
    qsub -N $sst_file -o ~/um_output/$basis-$sst_file $jobdir/umuisubmit_run
done

