#!/bin/bash

# Returns a list of files in SOURCEPATH that also exist in TARGETPATH. Uses md5
# checksums to identify duplicates.

# Use:
# find_duplicates SOURCEPATH [TARGETPATH]

# Scott Wales 2012-12-05

# Copyright 2012 ARC Centre of Excellence for Climate System Science
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sourcepath=$1
targetpath=${2:-$sourcepath}

checksums=$(find $targetpath -type f -exec md5sum {} \;)

for file in $(find $sourcepath -type f); do
	filesum=$(md5sum $file | awk '{print $1}')
	matches=$(echo "$checksums" | grep $filesum | awk '{print $2}')
	wasmatched=false

	for match in $matches; do
		# Check that the match isn't a symlink to $file
		if [ "$(readlink -f $match)" != "$(readlink -f $file)" ]; then
			echo "$file <- $match"
			wasmatched=true
		fi
	done
	
	# No match
	if [ $wasmatched == false ]; then
		echo $file
	fi
done

	
