#!/bin/bash
#
# ./um-dependancies
# Create a script that lists file dependancies of UMUI basis files.
#
# AUTHORS:
# Scott Wales <scott.wales@unimelb.edu.au>
# ARC Centre of Excellence for Climate System Science 
# <climate_help@nf.nci.org.au>
#
# Available at https://github.com/ScottWales/um-utils
#
# ----------------------------------------------------------------------
# Copyright 2012 ARC Centre of Excellence for Climate System Science
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------
#
# A script is created because environment variables may be set up differently
# on the local and remote machines. Running the script will produce a list of
# files. Note that even if a file is referenced in a UM basis that file may
# be ignored due to other configuration options.
#

function usage {
    echo "$0: Create a script to list UM file dependancies"
    echo "Usage: $0 INPUTS ... > OUTPUT"
    echo "INPUTS: UM basis files"
    echo "OUTPUT: Shell script that when run lists used files"
}

options=$(getopt --options h --longoptions help -- "$@")
eval set -- "$options"

while true; do
    case "$1" in
        -h|--help)
            usage; shift ;;
        --)
            shift; break ;;
    esac
done

if [ "$#" -lt 1 ]; then
    echo "No input" >&2
    exit 1
fi

# Hold parts in separate temp files, to be pasted together in the output
envar_name=$TMPDIR/$0-envname.$$
envar_val=$TMPDIR/$0-envval.$$
apath=$TMPDIR/$0-apath.$$
afile=$TMPDIR/$0-afile.$$
miscpath=$TMPDIR/$0-miscpath.$$
miscfile=$TMPDIR/$0-miscfile.$$

# Output script header
echo "#!/bin/bash"
cat << EOF
#
# Displays a list of files referenced in the UM basis files:
# $@
#

EOF

# Regulare expressions match 
# VAR = ' foo bar '
# VAR = ' one ',
#       ' two ',
#       ' three '
# Leading and trailing spaces are removed from values (internal spaces preserved)
# Matches are done between the variable declaration and the next line not ending with ,
function basis_var {
    file=$1
    var=$2
    # Match only multiple values
    sed -n $file -e '/\<'"$var"'=.*,\s*$/,/[^,]\s*$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?\s*$|\1|p'
    # Match only one value
    sed -n $file -e 's|\<'"$var"'\s*=\s*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*$|\1|p'
}
paste <(basis_var $1 ENVAR_NAME) <(basis_var $1 ENVAR_VAL) --delimiters="="

# Handle multiple basis files
for file in "$@"; do
    echo "#===================="
    echo "# $file";
    echo "#===================="

    echo "# UMUI Environment variables"
    paste <(basis_var $file ENVAR_NAME) <(basis_var $file ENVAR_VAL) --delimiters="="
    echo

    echo "# List of referenced files"
    echo "cat << EOF"

    # Ancillaries
    sed -n $file -e '/\<APATH=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' > $apath
    sed -n $file -e '/\<AFILE=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' > $afile
    paste --delimiters="/" $apath $afile
    echo

    # Hand edits
    sed -n $file -e '/\<HEDFILE=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p'
    echo

    # Stashmaster, User Stash and Stash Prognostics
    sed -n $file -e '/\<SMDIR=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1/STASHmaster_A|p'
    sed -n $file -e '/\<USERLST_A=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p'
    sed -n $file -e '/\<USRP_FILE_A=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p'
    echo

    # Override files
    sed -n $file -e '/\<UMCOMP_OP=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p'
    sed -n $file -e '/\<UFCOMP_OP=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p'
    echo

    # Misc files
    rm -f $miscpath $miscfile
    # Input Dump
    sed -n $file -e '/\<PATH21=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscpath
    sed -n $file -e '/\<FILE21=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscfile
    # LBCs
    sed -n $file -e '/\<PATH95=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscpath
    sed -n $file -e '/\<FILE95=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscfile
    # Radiation
    sed -n $file -e '/\<PATHSW=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscpath
    sed -n $file -e '/\<FILESW=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscfile
    sed -n $file -e '/\<PATHSW=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscpath
    sed -n $file -e '/\<FILESWD=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscfile
    sed -n $file -e '/\<PATHLW=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscpath
    sed -n $file -e '/\<FILELW=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscfile
    sed -n $file -e '/\<PATHLW=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscpath
    sed -n $file -e '/\<FILELWD=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscfile
    # Vert levels
    sed -n $file -e '/\<VLEV_PATH=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscpath
    sed -n $file -e '/\<VLEV_FILE=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscfile
    # Random Seed
    sed -n $file -e '/\<RSEED_PATH=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscpath
    sed -n $file -e '/\<RSEED_FILE=/,/[^,]$/s|.*'"'"'\s*\(\S\(.*\S\)\?\)\s*'"'"'\s*,\?.*|\1|p' >> $miscfile
    paste --delimiters="/" $miscpath $miscfile

    echo "EOF"
    echo
done

rm -f $envar_name $envar_val $apath $afile $miscpath $miscfile
